#!/bin/bash
ansibleVersion=$(ansible --version | grep -m 1 ansible)
if [ -n "$ansibleVersion" ]; then
    echo "OK -- $ansibleVersion"
    exit 0
else
    echo "CRITICAL -- ansible not found"
    exit 2
fi
