#!/bin/bash
ansibleVersion=$(ansible --version | awk '{print $2; exit}')
if [ "$ansibleVersion" ]; then
    echo "OK -- ansible version $ansibleVersion"
    exit 0
else
    echo "CRITICAL -- ansible not found"
    exit 2
fi
