#!/bin/bash
# define an acceptable threshold for remote connection count
count=
sshConnectionCount=$(w -i | sed 1,2d | awk '{print $3}' | wc -l)
if [[ "$sshConnectionCount" -gt $count ]]; then
   sshHosts=$(w -i | sed 1,2d | awk '{print $3}' | awk -vORS=, '{print $1}')
   echo "WARN -- $sshConnectionCount SSH Connections -- $sshHosts"
   exit 1
else 
   echo "OK -- $sshConnectionCount SSH Connections -- $sshHosts"
   exit 0
fi
